### ISSUE TITLE
Postgres DSN and config file Application Server

### ISSUE THREAD

**Issue by titansmc** [JohnRoesler/chirpstack-kubernetes#1]
Hi, thanks for the templates. I see you have a configmap that is mounted at /.config.... but you also have an envarionment variable for postgres dsn, which one is taking effect? I see errors like following when configuring the dsn in the confimap and also in the secret.

```
time="2020-11-24T23:21:21Z" level=warning msg="storage: ping PostgreSQL database error, will retry in 2s" error="parse \"postgresql://chirpstack:password@chirpstack-postgresql.chirpstack.svc.cluster.local/chirpstack_as\\n\": net/url: invalid control character in URL"
```

**Comment by titansmc** [comment]
I was missing 
```
echo -n
```
when creating the secret.

**Comment by JohnRoesler** [comment]
Thanks for noting what you found! 

That may be helpful for me to include here as well - some of the CI/CD type steps that support secrets and other ENV injection.
