### ISSUE TITLE
configMap not used in application server

### ISSUE THREAD

**Issue by titansmc** [JohnRoesler/chirpstack-kubernetes#2]
Hi,
I see that you are mounting the configmap in a location that is not taking effect, and you rather configure app server through environment variables. Why is that?

**Comment by JohnRoesler** [comment]
Hi @titansmc - thanks for bringing this up! The configmap should be mounted (and is for me) as per https://www.chirpstack.io/application-server/install/config/ `$HOME/.config/chirpstack-application-server/chirpstack-application-server.toml` is a valid location. However, it's totally possible $HOME isn't the same in every environment so I will update all the deployments to use the similar hard paths `/etc/chirpstack-application-server/chirpstack-application-server.toml`
