### ISSUE TITLE
initdb scripts for postgres

### ISSUE THREAD

**Issue by titansmc** [JohnRoesler/chirpstack-kubernetes#5]
Hi John,
I see that the docker-compose version comes with few postgres commands to initialize the DB schema.
https://github.com/brocaar/chirpstack-docker/tree/master/configuration/postgresql/initdb
Since I didn't deploy the whole stack yet, I am not sure if they are needed or can be skipped.
Cheers.

**Comment by JohnRoesler** [comment]
I suppose that depends on where your database runs. I ran pg separately and so I don’t believe I used the init scripts.
